name: shiny-deseq2

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  # base r environment
  - r-base=4.0
  - r-essentials=4.0  # this includes the tidyverse

  # extra packages
  - r-dt  # R to js DataTables
  - r-here

  # shiny
  - r-shiny
  - r-shinydashboard
  - r-shinycssloaders
  - r-shinyjs

  # DESeq2
  - r-biocmanager
  - bioconductor-deseq2
